version: '3'

services:
  email:
    container_name: 'email'
    build: .
    restart: always
    volumes:
      - ./:/email
    command: "python src/main.py"
    networks:
      - network
    depends_on:
      - rabbitmq

  rabbitmq:
    container_name: 'email-rabbitmq'
    image: rabbitmq:3.12.10-management
    hostname: ${RABBITMQ_HOST}
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - '${RABBITMQ_PORT}:5672'
      - '${RABBITMQ_INTERFACE_PORT}:15672'
    networks:
      - network


networks:
  network:
    external: true
    name: authentication_network
